### ISSUE TITLE
Bottom Padding Issue

### ISSUE THREAD

**Issue by jdsimcoe** [linuz90/better-roam-research#1]
So I've found that the newest "framed" theme has a weird `10px` bug at the bottom of the viewport:

![image](https://user-images.githubusercontent.com/275617/83427574-cb304d00-a3e5-11ea-9d3b-82c90bdd7cb2.png)

I've tried removing the `margin-top: 10px` from `.roam-center` and adding `padding-bottom: 10px` to `.roam-topbar` but neither of those seems to properly solve the bug. Just wanted to flag this for you.

**Comment by linuz90** [comment]
Very weird, checking.

**Comment by linuz90** [comment]
I'm not seeing this issue anymore, can you check now?

**Comment by jdsimcoe** [comment]
@linuz90 I don't see this anymore either. Nice!
