### ISSUE TITLE
block embed text in dark mode is unreadable

### ISSUE THREAD

**Issue by dpetruk** [linuz90/better-roam-research#10]
Issue:
![image](https://user-images.githubusercontent.com/30505853/86906246-f19b8380-c11b-11ea-9d38-37bc0edb9a48.png)

Temporary fix:
added parallel css formatting to fix it:
roam/css -> theme -> /code block (choose css) -> this code inside:
`
.rm-embed-container {
    background-color: #21282C;
}`
![image](https://user-images.githubusercontent.com/30505853/86906355-1abc1400-c11c-11ea-97c1-059d18ee05b4.png)

Result:
![image](https://user-images.githubusercontent.com/30505853/86906213-e6485800-c11b-11ea-9f08-738d60ad2275.png)

**Comment by linuz90** [comment]
Adding this fix today!
