### ISSUE TITLE
Unreadable tags when filtering pages

### ISSUE THREAD

**Issue by iamjli** [linuz90/better-roam-research#14]
Here's what it looks like for me: 
![image](https://user-images.githubusercontent.com/7219365/91592565-b99b0a80-e92c-11ea-940d-d2b50304fc54.png)

However, filtering linked references is fine: 
![image](https://user-images.githubusercontent.com/7219365/91592674-e7804f00-e92c-11ea-8278-67cb1f6c12fd.png)

**Comment by linuz90** [comment]
Fixed today.
