### ISSUE TITLE
Disappearing topbar and keyboard shortcuts issue

### ISSUE THREAD

**Issue by danielguillan** [linuz90/better-roam-research#15]
Better Roam Research now hides Roam's topbar and shows it only when the cursor hovers over it. This introduces an issue when using keyboard shortcuts for interacting with the items in the topbar. For example, `cmd+u` triggers full text search by focusing the search input, but it becomes unusable as the topbar remains hidden.

Any chance we can find a workaround for this or revert the change until there's a better solution? Thank you!

**Comment by wgoodall01** [comment]
I'm also experiencing this issue.

For now, an easy workaround is just to reference the previous version's source in your `roam/css` page, through a Git CDN, like so:

```css
@import url("https://raw.githack.com/linuz90/better-roam-research/1a2d1aff771dde976887188b4b218a927b81eb63/main.css");
```

**Comment by linuz90** [comment]
Thanks for the comments, removed this behaviour today.
