### ISSUE TITLE
Block reference usage count obscured while using dark mode

### ISSUE THREAD

**Issue by boolbaall** [linuz90/better-roam-research#16]
Expected behaviour (as seen in sidebar, default theme) - block referenced ones somewhere else in graph
<img width="547" alt="Screen Shot 2020-09-10 at 09 57 40" src="https://user-images.githubusercontent.com/46777772/92706947-d3851600-f34c-11ea-8e70-e773608dadf7.png">
Actual behaviour (as seen in sidebar, Better Roam Research) - block reference count missing
<img width="547" alt="Screen Shot 2020-09-10 at 09 58 17" src="https://user-images.githubusercontent.com/46777772/92706983-db44ba80-f34c-11ea-9b21-2b777d206497.png">
Block reference count only appears when hovered over
<img width="562" alt="Screen Shot 2020-09-10 at 09 58 42" src="https://user-images.githubusercontent.com/46777772/92707007-e0096e80-f34c-11ea-81b4-d0425d4caf86.png">

**Comment by linuz90** [comment]
Fixed, thanks!

**Comment by boolbaall** [comment]
Thanks! Not seeing it reflected in my system yet, is there anything I need to do to refresh it? I thought it theme updated automatically.
