### ISSUE TITLE
Block Embed bug??

### ISSUE THREAD

**Issue by CherryC99** [linuz90/better-roam-research#18]
Is this a bug when I make a [block embed], the background in the [block embed] is dark even if OS is in Light Mode?

**Comment by linuz90** [comment]
Yep, I'll fix it soon!

**Comment by lalabeau** [comment]
Thank you so much for your quick response and great work! Really appreciate it !

**Comment by charleshl** [comment]
Not fixed yet?

**Comment by linuz90** [comment]
Fixed, sorry for the delay!
