### ISSUE TITLE
Delete Page modal is not visible

### ISSUE THREAD

**Issue by axelav** [linuz90/better-roam-research#2]
The confirmation modal is hidden when using this theme. I can look into it a bit during the week but wanted to note the issue. 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/59404/83979803-f41d7a00-a8de-11ea-80b6-32b45706e212.png">

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/59404/83979794-d8b26f00-a8de-11ea-95cd-4c1188aee53f.png">

**Comment by jdsimcoe** [comment]
@linuz90 The same goes for the `Export All` modal. Any modals that show up via `.bp3-dialog` are not showing.

**Comment by linuz90** [comment]
Fixed!
