### ISSUE TITLE
Kanban Board visual bug dark mode

### ISSUE THREAD

**Issue by silashowe-cc** [linuz90/better-roam-research#20]
The kanban board doesn't have a dark theme, which in my opinion isn't a huge deal. The bigger problem in my eyes is that the font at the top of each column on the board is white against a light grey background.
![Screen Shot 2020-09-23 at 10 25 08 PM](https://user-images.githubusercontent.com/70595560/94100782-a5dbaa80-fdeb-11ea-9afc-187247e0be06.png)

**Comment by linuz90** [comment]
Hey, just restyled the kanban, now it looks like this and has a great dark mode:

<img width="766" alt="CleanShot 2020-09-24 at 07 50 25@2x" src="https://user-images.githubusercontent.com/9629188/94105981-c54df400-fe3a-11ea-8bcd-080ae7349461.png">

What do you think?

**Comment by silashowe-cc** [comment]
Looks super clean!
________________________________

**Comment by linuz90** [comment]
Awesome, closing this ✨
