### ISSUE TITLE
Quick capture sync colors need fixing in dark mode

### ISSUE THREAD

**Issue by vkazartsev** [linuz90/better-roam-research#21]
As stated

![image](https://user-images.githubusercontent.com/57834450/94515457-438c0b00-022c-11eb-92ed-0751cc0a9d21.png)

**Comment by linuz90** [comment]
Hi, any idea on how to trigger this on desktop? I can only open it on mobile so hard to debug.

**Comment by vkazartsev** [comment]
On mobile roamresearch.com defaults to the Quick Capture screen (you can switch to full though — and back).

Whatever notes you make there will get synced to your graph once you refresh a roam page in a desktop browser.

That's when you get to see the pop-up with broken colors

**Comment by linuz90** [comment]
Oh got it, should be fixed now!

**Comment by vkazartsev** [comment]
Works, thx 😊
