### ISSUE TITLE
Theme not applied via @import as of this morning

### ISSUE THREAD

**Issue by minimaldesign** [linuz90/better-roam-research#22]
copy + pasting the whole `main.css` file seems to fix the issue. Importing other themes also seem to be working. Didn't investigate further… Thanks!

**Comment by jacobtfisher** [comment]
Same issue for me, with same fix.

**Comment by nstafie** [comment]
Seems like the link is actually dead, that's why it doesn't import anything. The best way to fix it, for now, is to copy & paste the whole `main.css` file in.

**Comment by linuz90** [comment]
I've deleted an old css file that lived in a subfolder yesterday, have you tried using the new URL in the Readme?

**Comment by linuz90** [comment]
Oh just realized the link is wrong there, I'll fix it. Correct one is: [https://linuz90.github.io/better-roam-research/main.css](https://linuz90.github.io/better-roam-research/main.css)

**Comment by DaviRolim** [comment]
The javascript seems to be working great. I can pause the video, I can add the timestamp, but the play button before the timestamp doesn't show up, anyone had a similar problem? 
![image](https://user-images.githubusercontent.com/19915084/118195160-138f2200-b421-11eb-987b-170e9f9d541c.png)
