### ISSUE TITLE
Looks like the update yesterday broke system-level dark mode

### ISSUE THREAD

**Issue by mcburden** [linuz90/better-roam-research#23]
I'm using MacOS in fixed dark mode. This morning I'm seeing all white.

Edit: I'm importing the CSS from the URL with minimal customizations:
<img width="766" alt="2020-10-15_10-11-16" src="https://user-images.githubusercontent.com/325631/96141317-e1d7cc00-0ece-11eb-9f99-690062ccbc7c.png">

**Comment by HarryAmmon** [comment]
Looks like the deploy to GitHub pages has failed or the URL has changed. Getting a 404 with that URL. A quick fix that has worked for me:

 - create a new top-level block in [[roam/css]] can title it anything you like,
- copy and past the contents of main.css in a code block as a child of the top-level block you've just made
- boom

**Comment by HarryAmmon** [comment]
A fix is mentioned in #22

**Comment by mcburden** [comment]
My bad. I _did_ compare the URLs, but apparently not too closely 🤦 

old: 
https://linuz90.github.io/better-roam-research/src/css/main.css
new: 
https://linuz90.github.io/better-roam-research/main.css

**Comment by linuz90** [comment]
Sorry for the confusion with the link change, but now there's just one file and it will always be updated.
