### ISSUE TITLE
CSS file is 404

### ISSUE THREAD

**Issue by pacocoursey** [linuz90/better-roam-research#25]
Previously was using this theme from the URL `https://linuz90.github.io/better-roam-research/src/css/main.css`, which is now 404. Didn't realized it had moved – might want to setup a redirect to avoid breaking existing themes!

**Comment by linuz90** [comment]
Hi Paco, you're right, I'm looking now if there's a way to do this with GitHub pages, where I'm hosting it.

**Comment by linuz90** [comment]
Fixed with a simple css file at the old URL that imports the new one. Can't believe I didn't think about this before. Thanks again for this report!
