### ISSUE TITLE
Block references aren't shown properly in Dark mode

### ISSUE THREAD

**Issue by jenningsb2** [linuz90/better-roam-research#26]
When in dark mode, the block references do not properly appear. (white text on a white background)
![84C0B2F7-D724-429F-A7F2-32C867D52700](https://user-images.githubusercontent.com/29644050/97433509-0337af80-18f4-11eb-97c0-5729355bf61f.jpeg)

**Comment by linuz90** [comment]
Hi, I'm trying to reproduce this issue but I can't. When I click on that references button, they open in the sidebar, so I can't see that wrong embed block. Any idea on how to reproduce it?

**Comment by jenningsb2** [comment]
Update your roam! I think the behavior is on a new version.

**Comment by jhong123** [comment]
I have the same problem.
Version 0.7.5-41613cc4

**Comment by linuz90** [comment]
Just fixed this, sorry about the delay!
