### ISSUE TITLE
Broken shared page

### ISSUE THREAD

**Issue by alanzchen** [linuz90/better-roam-research#29]
<img width="1563" alt="Screen Shot 2020-11-02 at 12 07 59 AM" src="https://user-images.githubusercontent.com/2144783/97835349-8fa0f400-1c9f-11eb-9dfc-011dd5491f74.png">

If you share a page in public, this is how it looks.

**Comment by alanzchen** [comment]
OK it seems like that the public page will not follow the `roam/css` filter, so any customization there will be enabled regardless of whether they are hidden or not. Never mind!

However, I do think that there is room for improvement of this theme when an individual page is shared publicly. Perhaps hide the sidebar in this case?
<img width="1563" alt="Screen Shot 2020-11-02 at 12 52 52 AM" src="https://user-images.githubusercontent.com/2144783/97838425-c974f900-1ca5-11eb-9561-dd316128e0d0.png">

**Comment by linuz90** [comment]
Absolutely, that's a good idea. Will look into this!

**Comment by linuz90** [comment]
Should have fixed this today.
