### ISSUE TITLE
Suggestion: Colored Tags and Kanban Blocks

### ISSUE THREAD

**Issue by silashowe-cc** [linuz90/better-roam-research#30]
I've started using colored tags. I've been doing this by having my own css code after the import line for your theme. 
```
@import url("https://linuz90.github.io/better-roam-research/main.css");
/* Custom data tags From Leyendecker Theme*/
span.rm-page-ref[data-tag="iCIMS"] {
    background: #5fa7ad !important;
    color: white !important;
    padding: 3px 7px;
    border-radius: 5px;
    line-height: 2em;
    font-weight: 500;
}
...
```
I think a great feature of your theme would be the ability to change the color of a Kanban block to match the color of the tag. Maybe just outline it in that color? Something along those lines could make the Kanban board easier to search for a certain colored tag.
I realize this is  a bit farfetched since your theme doesn't have its own implementation of colored blocks (I think), but I thought it would be really cool if you were able to get this working.

## My Current Kanban set up:
<img width="713" alt="Screen Shot 2020-11-20 at 1 58 53 PM" src="https://user-images.githubusercontent.com/70595560/99849519-f431cf00-2b38-11eb-9140-654a5c3233c2.png">

**Comment by hanct** [comment]
I second vote on this.  I like this idea.
