### ISSUE TITLE
Add .rm-alias-block to the :not selector for showing external link svg

### ISSUE THREAD

**Issue by tylerwince** [linuz90/better-roam-research#31]
Today, the theme will add a little link icon next to any external link but excludes any "link" that is actually just an alias to a page.

`[this shows the link icon](https://google.com)`
`[this does not show the link icon]([[November 23rd, 2020]])`

It would be nice if this applied to block references as well as page references.

`[this currently shows a link icon but likely shouldn't](((44RcQMcMq)))`

Here is the part of the codebase that likely needs changing: 
https://github.com/linuz90/better-roam-research/blob/1a63199b6a3236bf895a2169f9732c139e1122f9/main.css#L168

**Comment by linuz90** [comment]
Fixed, thanks!
