### ISSUE TITLE
Block quote

### ISSUE THREAD

**Issue by nepahwin** [linuz90/better-roam-research#33]
You don't seem to support block quotes yet—the formatting looks a little odd. This would be nice :)

Nice theme though—thanks.

![Screenshot 2020-12-08 at 12 13 37](https://user-images.githubusercontent.com/379953/101482562-cfb65f00-394e-11eb-9dfe-1b46c668b6f2.png)

**Comment by linuz90** [comment]
Thanks! And good catch, just styled these.
