### ISSUE TITLE
Text in Header blocks is un-styled

### ISSUE THREAD

**Issue by Tohsig** [linuz90/better-roam-research#38]
## Description
It seems that `H1`, `H2`, and `H3` blocks are not being styled in the latest versions of Roam and Better Roam Research. I didn't dive too deep, but I'm wondering if it's tied to some of the [changes to roam/css](https://roamresearch.com/#/app/help/page/Ccg6sUgNQ) they made on December 14th. 

- **Roam Version:** `0.7.6-3f864e82`
- **BRR Version:** `main`
- **OS Tested:** macOS Catalina and Big Sur
- **Browsers Tested:** Safari 14, Firefox 85, Chrome 87

## Screenshots
<img width="475" alt="better-roam-research-off" src="https://user-images.githubusercontent.com/5247935/102388802-40d5c200-3fa0-11eb-9eef-a7e920e8decd.png">
<img width="366" alt="better-roam-research-on" src="https://user-images.githubusercontent.com/5247935/102388805-416e5880-3fa0-11eb-9b17-9c93d9298cc1.png">

**Comment by linuz90** [comment]
Good catch, thanks! Fixed.
