### ISSUE TITLE
Graph cannot display its full width

### ISSUE THREAD

**Issue by Zyst** [linuz90/better-roam-research#4]
The CSS at (I believe it's this one): https://github.com/linuz90/better-roam-research/blob/master/main.scss#L58-L61

Prevents the graph from displaying completely:

![image](https://user-images.githubusercontent.com/3832380/84226925-b9ffd400-aaa8-11ea-90f6-cea4d058b3d7.png)

**Comment by alanzchen** [comment]
I second this. What was the purpose of these lines at https://github.com/linuz90/better-roam-research/blob/master/main.scss#L58-L61?

Removing them seems just fine.

**Comment by linuz90** [comment]
These were to tweak the width of the text but might be obsoleted, I'll check it out.

**Comment by ethan-voon** [comment]
Came here to bring this up, looks like it's known.

Thanks a ton for writing this theme @linuz90 !

**Comment by alanzchen** [comment]
Since @frankdilo seems to be too busy to fix this at this point, feel free to use my fork temporarily.

```css
@import url("https://alanzchen.github.io/better-roam-research/src/css/main.css");
```

Roam Research also introduces a graph switcher menu, which slightly breaks this theme. You can add

```css
.rm-db-title-container {
  display: none !important;
}
```

to hide the swither.

**Comment by linuz90** [comment]
Sorry for the delay, I'll batch fix everything before the weekend!

**Comment by alanzchen** [comment]
> Sorry for the delay, I'll batch fix everything before the weekend!

Any update? @linuz90

**Comment by linuz90** [comment]
> > Sorry for the delay, I'll batch fix everything before the weekend!
> 
> 
> Any update? @linuz90 

Still haven’t had the time but plan on fixing a bunch of things in a matter of days, thanks for you patience!

**Comment by linuz90** [comment]
Finally fixed this and a bunch of other bugs. Pushing changes now. Please report if you spot other issues, and thanks so much for the patience!
