### ISSUE TITLE
Highlight text in darkmode

### ISSUE THREAD

**Issue by b1uegh0st** [linuz90/better-roam-research#40]
Hi, thanks for the theme.

I tried it in darkmode, somehow the highlight text looks like this. It is not like your preview picture. Is it a bug or did Roam change something?

![image](https://user-images.githubusercontent.com/6695697/103081886-82ebad00-460b-11eb-9a03-bc9af67db42d.png)

**Comment by usmansheikh** [comment]
Facing the same issue. Looking forward to seeing this resolved too.

**Comment by keikhcheung** [comment]
Change `.roam-highlight` to `.rm-highlight` [here](https://github.com/linuz90/better-roam-research/blob/f47adc0a5d7002463f52fa982d2363beb61c90f6/main.css#L509) will resolve this for now until PR #42 is merged.

**Comment by usmansheikh** [comment]
Awesome! Thank you. Works now.

**Comment by linuz90** [comment]
Fixed!
