### ISSUE TITLE
Missing dark theme styling for the Collapsible Parentheticals

### ISSUE THREAD

**Issue by watou** [linuz90/better-roam-research#44]
Missing dark theme styling for the new Collapsible Parentheticals feature in both collapsed 𐃏 and ((non-collapsed)) forms.

Wondering if #37 was closed without fixing this means you intend to leave some styling unhandled/not working?

**Comment by linuz90** [comment]
I didn't close the original issue, I'll fix this 👌

**Comment by linuz90** [comment]
Fixed!
