### ISSUE TITLE
Queries in darkmode

### ISSUE THREAD

**Issue by joukevandermaas** [linuz90/better-roam-research#47]
The frame around queries is very bright in dark mode. Preferably it would be de-emphasized and colored darker like the blocks themselves.

**Comment by linuz90** [comment]
Can you show me an example? I don't think I'm using this feature.

**Comment by joukevandermaas** [comment]
There are some examples on [this page](https://roamresearch.com/#/app/help/page/GM7GgD0AQ) of the help database.

In dark mode it looks like this:

![image](https://user-images.githubusercontent.com/1257578/106435889-b8d64980-6473-11eb-9d8c-9e1ba82a1ff0.png)

**Comment by tschoffelen** [comment]
Some custom CSS I use for this:

```
.rm-query {
    border: 1px solid #3d3d3d;
    border-radius: 6px;
}

.rm-query .rm-query-title {
    background-color: #2f2f2f;
    color: #a67aa7;
    border-top-left-radius: 6px;
    border-top-right-radius: 6px;
}
```

<img width="713" alt="image" src="https://user-images.githubusercontent.com/666220/110543441-3bf95800-8122-11eb-868c-65138d5d7598.png">

**Comment by linuz90** [comment]
Just fixed this, thanks!
