### ISSUE TITLE
Adjustable font size

### ISSUE THREAD

**Issue by joukevandermaas** [linuz90/better-roam-research#48]
I have some trouble reading off a screen so I prefer to increase font size of blocks. I don't really like using zoom because it also zooms in the chrome (such as the search bar), which leaves less space for the actual work.

I added this below the import line on the [[roam/css]] page:

```css
:root {
  --font-size: 15pt;
}
```

Which *mostly* works, but there are a few issues:

1. The bullet points are now misaligned from the block they belong to
2. The sidebar text doesn't resize at all

It would be nice if there was a css variable I could tweak that would adjust the text size for blocks (both in the main area as well as the sidebar) while leaving everything else as normal.

If you're not interested in implementing this feel free to close this issue, I just thought it might be something other people want as well.

**Comment by linuz90** [comment]
Don't have time for this now so closing it, but taking a note for the future, great idea!
