### ISSUE TITLE
dark.css (forced theme) doesn't have --accent-color

### ISSUE THREAD

**Issue by KUR-creative** [linuz90/better-roam-research#49]
![image](https://user-images.githubusercontent.com/20921187/106541793-f4d9df00-6545-11eb-9339-a83587d24fb7.png)

`https://linuz90.github.io/better-roam-research/dark.css` doesn't have `--accent-color` declaration.

So, the color of the link was displayed in white. 
There is `--accent-color` in light.css, but not in dark.css. 
It seems to be a mistake.

**Comment by linuz90** [comment]
Should be fixed now, thanks!
