### ISSUE TITLE
missing style in help panel view 

### ISSUE THREAD

**Issue by dtksi** [linuz90/better-roam-research#54]
![Screenshot 2021-02-23 at 10 20 42](https://user-images.githubusercontent.com/77235008/108823562-e456da80-75c0-11eb-9bbb-743c4c1fc9bf.png)

css quick fix => 
```
#app > div > div.rm-help-popup.react-draggable > div.react-resizable > div.rm-help-results > div.rm-help__left-panel.sticky > div.rm-help-categories {
  color: black
}
```

![Screenshot 2021-02-23 at 10 22 23](https://user-images.githubusercontent.com/77235008/108823680-0d776b00-75c1-11eb-97d5-bf9158d64320.png)

**Comment by linuz90** [comment]
Fixed, thanks!
