### ISSUE TITLE
Text max-width conflicts with new feature to adjust page width

### ISSUE THREAD

**Issue by dimfeld** [linuz90/better-roam-research#56]
This line in the CSS causes issues when "large" or "full" width is chosen in the new page width selector. In my roam/css I just overrode the value from the stylesheet to `unset` but we may want to consider removing it from the CSS here. Happy to submit a PR if you agree.

https://github.com/linuz90/better-roam-research/blob/575c32b384a956f1ece4545e65e60dbb567c427b/main.css#L509

**Comment by joshbrake** [comment]
@dimfeld Was having trouble tracking down why the text in my blocks wasn't extending to the full width and noticed the same thing.

**Comment by linuz90** [comment]
Fixed! (Removed my code)

**Comment by dimfeld** [comment]
Looks good here. Thank you!
