### ISSUE TITLE
TODO checkbox is misaligned in kanban item

### ISSUE THREAD

**Issue by helloworld** [linuz90/better-roam-research#57]
![image](https://user-images.githubusercontent.com/3893054/112595206-77617b00-8de0-11eb-8170-053fcca9e2dd.png)

When you have a `{{TODO}}` in a kanban item, the check box is misaligned.

**Comment by helloworld** [comment]
Here's the custom CSS I'm using to clean up checkboxes:

```
.kanban-board .kanban-column .kanban-card .check-container {
	margin-bottom: 0px !important;
  	margin-right: 2px;
}

span.checkmark {
	top: 0px;
}
```

Happy to send a PR if you agree!

**Comment by linuz90** [comment]
Fixed!
