### ISSUE TITLE
Merge page modal in Dark mode is not visible

### ISSUE THREAD

**Issue by eduardoi** [linuz90/better-roam-research#6]
Merge modal popup in dark mode is not visible.

**Comment by linuz90** [comment]
What popup are you referring to? I'll try to fix this today.

**Comment by benwf** [comment]
E.g. if you're trying to delete a file. Switching to any other theme reveals it then.

**Comment by eduardoi** [comment]
![Untitled](https://user-images.githubusercontent.com/3464919/86242741-75e28980-bba5-11ea-9657-0be19dc4654f.png)
On chrome (Version 83.0.4103.116 (Official Build) (64-bit)) when merging two pages the modal warning message (attached) is not represented. (at least in my setup)

**Comment by eduardoi** [comment]
btw Fabrizio, thanks for your work!

**Comment by linuz90** [comment]
You're welcome! Should be fixed now, pushing updates in a few minutes.
